apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  hostPath:
    path: /pv/data-analytics
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
