## create name space
apiVersion: v1
kind: Namespace
metadata:
  name: temp-bus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finance-saleh
  name: finance-saleh
  namespace: temp-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-saleh
  strategy: {}
  template:
    metadata:
      labels:
        app: finance-saleh
    spec:
      containers:
      - image: redis:alpine
        name: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
