# Create 5 nginx pods in which two of them is labeled env=prod and 
# three of them is labeled env=dev

# Create 5 nginx pods in which two of them is labeled env=prod and 
# three of them is labeled env=dev
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-1
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app-prod-1
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-2
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: app-prod-2
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev-1
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: app-dev-1
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev-2
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: app-dev-2
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev-3
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: app-dev-3
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-prod-1
# spec:
#   selector:
#     matchLabels:
#       env: prod
#   template:
#     metadata:
#       labels:
#         env: prod 
#     spec:
#       containers:
#       - name: app-prod-1
#         image: nginx
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-prod-2
# spec:
#   selector:
#     matchLabels:
#       env: prod
#   template:
#     metadata:
#       labels:
#         env: prod 
#     spec:
#       containers:
#       - name: app-prod-2
#         image: nginx
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
# --- 

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-dev-1
# spec:
#   selector:
#     matchLabels:
#       env: dev
#   template:
#     metadata:
#       labels:
#         env: dev 
#     spec:
#       containers:
#       - name: app-dev-1
#         image: nginx
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
# --- 
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-dev-2
# spec:
#   selector:
#     matchLabels:
#       env: dev
#   template:
#     metadata:
#       labels:
#         env: dev 
#     spec:
#       containers:
#       - name: app-dev-2
#         image: nginx
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
# --- 

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-dev-3
# spec:
#   selector:
#     matchLabels:
#       env: dev
#   template:
#     metadata:
#       labels:
#         env: dev 
#     spec:
#       containers:
#       - name: app-dev-3
#         image: nginx
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
