apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
            cpu: 500m
            memory: 128Mi
    env:
      - name: KEY_1
        valueFrom:
          configMapKeyRef:
            name: keyvalcfgmap
            key: key1
      - name: KEY_2
        valueFrom:
          configMapKeyRef:
            name: keyvalcfgmap
            key: key2
            
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
