apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-saleh
spec:
  containers:
  - image: redis:alpine
    name: redis-storage-saleh
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
    volumeMounts:
    - mountPath: /data/redis
      name: redis-storage-saleh
  volumes:
  - name: redis-storage-saleh
    emptyDir: {}
    