# 6. Create a service messaging-service to expose the messaging application within the cluster on port 6379.
# a. Service: messaging-service
# b. Port: 6379
# c. Type: ClusterIp
# d. Use the right labels

apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging
    tier: msg
  name: messaging-service 
spec:
  selector:
    app: messaging
    tier: msg
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP