apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging
    tier: msg
  name: messaging-service 
spec:
  selector:
    app: messaging
    tier: msg
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP